<?xml version="1.0"?>
<!DOCTYPE Bienes[
<!ELEMENT Bienes (Producto|Servicio)*>
<!ELEMENT Producto (Descripcion?, Componentes?,Recomendaciones?,Proovedor?)>
<!ELEMENT Componentes (Componente+)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Componente (#PCDATA)>
<!ELEMENT Servicio (Insumos, Recomendaciones?)>
<!ELEMENT Insumos (Insumo)+>
<!ELEMENT Insumo EMPTY>
<!ELEMENT Alquiler (Insumo)>
<!ELEMENT Recomendaciones (#PCDATA)>
<!ATTLIST Producto codigo ID #REQUIRED>
<!ATTLIST Producto nombre CDATA #REQUIRED>
<!ATTLIST Producto precioVenta CDATA #IMPLIED>
<!ATTLIST Producto existencias CDATA #REQUIRED>
<!ATTLIST Producto precioCompra CDATA #IMPLIED>
<!ATTLIST Proovedor nit CDATA #REQUIRED>
<!ATTLIST Proovedor precioActual CDATA #IMPLIED>
<!ATTLIST Servicio codigo ID #REQUIRED>
<!ATTLIST Servicio nombre CDATA #REQUIRED>
<!ATTLIST Servicio precioVenta CDATA #IMPLIED>
<!ATTLIST Servicio manoObra CDATA #IMPLIED>
<!ATTLIST Servicio tiempoEsperado CDATA #IMPLIED>
<!ATTLIST Insumo producto IDREF #REQUIRED>
<!ATTLIST Insumo unidades CDATA #IMPLIED>
<!ATTLIST Alquiler codigo ID #REQUIRED>
<!ATTLIST Alquiler nombre CDATA #REQUIRED>
<!ATTLIST Alquiler precioAlquiler CDATA #IMPLIED>
<!ATTLIST Alquiler tiempoAlquiler CDATA #IMPLIED>
]>
<Bienes>
	<Producto codigo="C25369" nombre="Líquido para vidrios" precioVenta="20000" existencias="10"
	precioCompra="18000">
		<Descripcion> La esponja esta cubierta en nylon. Largo de esponja y escurridor de caucho: 8
		pulgadas. En Unidad.
		</Descripcion>
		<Proovedor nit="123" precioActual="5000"/>
	</Producto>
	<Producto codigo="C493256" nombre="Jabón en polvo" precioVenta="2000" existencias="100"
	precioCompra="18000">
		<Recomendaciones>No dejar al alcance de los niños
		</Recomendaciones>
		<Proovedor nit="123" precioActual="2500"/>
	</Producto>
	<Producto codigo="C32014" nombre="Limpiador con caucho y esponja" precioVenta="50000">
		<Componentes>
		<Componente> AGUA 930 c.c. </Componente>
		<Componente> COLOR - ANILINA (VEGETAL) 1 Gramo </Componente>
		<Componente> GENAPOL LRO 1 c.c. EDTA 1 c.c. </Componente>
		<Componente> MERGAL 1 c.c. </Componente>
		<Componente> BUTIL CELLOSOLVE 50 c.c. </Componente>
		<Componente> ALCOHOL ISOPROPILICO 20 c.c </Componente>
		</Componentes>
		<Proovedor nit="23423" precioActual="15000"/>
	</Producto>
	<Servicio codigo="LVEDA" nombre="Lavado vidrios edificios" precioVenta="500000" manoObra="100000" tiempoEsperado ="60">
		<Insumos>
			<Insumo producto="C25369" unidades="10"></Insumo>
			<Insumo producto="C32014" unidades="2"></Insumo>
		</Insumos>
		<Recomendaciones>En edificios de más de cinco pisos usar andamios tipo B
		</Recomendaciones>
	</Servicio>
	<Servicio codigo="LPISO" nombre="Limpieza pisos acrilicos" precioVenta="40000" manoObra="5000">
		<Insumos>
			<Insumo producto="C25369" unidades="10"></Insumo>
			<Insumo producto="C493256" unidades="1"></Insumo>
		</Insumos>
		<Recomendaciones>En edificios de más de cinco pisos usar andamios tipo B
		</Recomendaciones>
	</Servicio>
	<Alquiler codigo="A2371623" nombre="Alquiler de Jabon" precioAlquiler="15000" tiempoAlquiler="3">
		<Insumos>
			<Insumo producto="C25369" unidades="10"></Insumo>
		</Insumos>
	</Alquiler>
</Bienes>